version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgresql
    restart: unless-stopped
    environment:
      POSTGRES_USER: pinxiang
      POSTGRES_PASSWORD: pinxiang
      POSTGRES_DB: pinxiang_database
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: